### ISSUE TITLE
Can't watch JS files for changes

### ISSUE THREAD

**Issue by BurningDog** [Snapstromegon/eleventy-plugin-rollup#7]
When I run eleventy with `eleventy --serve` I would like to make changes in my JS file and have `Rollup` automatically pick up those changes, rebuild the destination JS file, and have browsersync refresh the browser. This doesn't work - Rollup doesn't pick up changes to the JS file. I have to restart `eleventy --serve` on the command line each time I make changes to JS files.

https://rollupjs.org/guide/en/#watch-options specifies that Rollup will watch the specified input files for changes, but:

```
These options only take effect when running Rollup with the --watch flag, or using rollup.watch.
```

How do I run Rollup in `watch` mode?

My `.eleventy.js` file reads:

```js
eleventyConfig.addPlugin(rollupPlugin, {
  rollupOptions: {
    output: {
      format: 'es',
      dir: 'dist/js',
    },
    watch: {
      include: [
        'src/js/*'
      ]
    }
  },
});
```

However, I can't see how to invoke `Rollup` via `eleventy-plugin-rollup` in `watch` mode.

**Comment by Snapstromegon** [comment]
Hi @BurningDog,

this plugin does not use the rollup watch mode on purpose, as it's supposed to be highly integrated into the 11ty workflow.

This means that for each build (and watch build of 11ty) a new rollup build instance is created.

You should be able to resolve this issue by adding a watch target to your js files in your eleventy config.

You can see the [11ty docs here](https://www.11ty.dev/docs/watch-serve/#add-your-own-watch-targets)

Code example:
```js
// .eleventy.js
module.exports = function(eleventyConfig) {
  eleventyConfig.addWatchTarget("src/js/");
};
```

Please add a short response wether this helped you so I can close the issue or otherwise can investigate further.

**Comment by BurningDog** [comment]
Ah brilliant, this worked perfectly, thank you! Will close the issue. It would be great to have this added to the `README` too.

**Comment by Snapstromegon** [comment]
Just FYI:
Version 1.1.0 of this plugin now does a best effort to parse the rollup config watch target - the approach described above is still the recommended way of doing things.
